import Head from 'next/head'
import Image from 'next/image'
import BlockCard from '../components/BlockCard'
import styles from '../styles/Home.module.css'
// create a component return image with get image url from props
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <div className="grid grid-cols-3 divide-x h-screen">
        <div className="bg-sky-500/75 items-center justify-center flex flex-col">
        <BlockCard image="https://images.edrawsoft.com/images2020/instances.jpg" text="sdadfsjdhbfjshdbfl "/>
            </div>
        <div className="bg-red-200 items-center justify-center flex flex-col">       
        <BlockCard image="https://images.edrawsoft.com/images2020/icon/aws-lambda.jpg" text="bişiyler falan işte ddfnjsdf "/>
        <BlockCard image="https://images.edrawsoft.com/images2020/icon/aws-lambda.jpg" text="bişiyler falan işte df"/>
        <BlockCard image="https://images.edrawsoft.com/images2020/icon/aws-lambda.jpg" text="bişiyler falan işte df"/>
        <BlockCard image="https://images.edrawsoft.com/images2020/icon/aws-lambda.jpg" text="bişiyler falan işte df"/>
            </div>
        <div className="bg-teal-900	items-center justify-center flex flex-col ">
        <BlockCard image="https://images.edrawsoft.com/images2020/instance.jpg" text="bişiyler falan işte df"/>
        <BlockCard image="https://images.edrawsoft.com/images2020/instance.jpg"  text="bişiyler falan iştedf "/>
        <BlockCard image="https://images.edrawsoft.com/images2020/instance.jpg " text="bişiyler falan işte df "/>
        <BlockCard image="https://images.edrawsoft.com/images2020/instance.jpg" text="bişiyler falan işte  sdgdsfgdfg  "/>

          
          </div>
      </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
